#!/bin/bash

function term_init() {
    termmem -i -f $TERM_FILE
}

# usage: term_search KEY
function term_search() { #1
    key=$1

    export PREV_TERM_KEY=$key
    tmux send-keys -t $TERM_PANE "search " "$key" Enter
}

function term_insert() { #12
    key=$1
    val=$2

    tmux send-keys -t $TERM_PANE "insert " "$key" " $val" Enter
}

function term_update() { #12
    key=$1
    val=$2

    tmux send-keys -t $TERM_PANE "update " "$key" " $val" Enter
}

function term_remove() { #1
    key=$1

    tmux send-keys -t $TERM_PANE "remove " "$key" Enter
}

function term_append() { #12
    key=$1
    val=$2

    tmux send-keys -t $TERM_PANE "append " "$key" " $val" Enter
}

function term_save() {
    tmux send-keys -t $TERM_PANE "save" Enter
}

function term_apply() {
    termmem "search" $PREV_TERM_KEY
}

function term_quit() {
    tmux send-keys -t $TERM_PANE "quit" Enter
}
